[profile.default]
gas_reports = ["TokenA"]
libs = ["lib"]
out = "out"
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']
src = "src"

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}"}
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
